course = 'mooc-data-analysis-with-python-2022'
[exercises.part01-e01_hello_world]
id = 188742
checksum = 'd1d374bd30e433577180e0289b4be079'

[exercises.part01-e02_compliment]
id = 188737
checksum = 'c5b3871c139657c1bd2bf79c49f2f6bb'

[exercises.part01-e03_multiplication]
id = 188729
checksum = 'f69a5426ffbff2cc746e4285816a0257'

[exercises.part01-e04_multiplication_table]
id = 188735
checksum = 'd1d91f3667809648fadacaef3f739f2c'

[exercises.part01-e05_two_dice]
id = 188732
checksum = '00ef52530f7d2abdf074b298874d8d4d'

[exercises.part01-e06_triple_square]
id = 188728
checksum = '7fe79f74f0e180c9ed8faf3ebe7c71b6'

[exercises.part01-e07_areas_of_shapes]
id = 188727
checksum = '6bd56dee9f99a21cd9391f0f112616a4'

[exercises.part01-e08_solve_quadratic]
id = 188731
checksum = '9d476518b7a4c08619dbade352cc0d06'

[exercises.part01-e09_merge]
id = 188740
checksum = 'c33fc086579ab6e13cb1e5e8922a9080'

[exercises.part01-e10_detect_ranges]
id = 188739
checksum = '762b151f74abcf56116cd5506aab855a'

[exercises.part01-e11_interleave]
id = 188741
checksum = '858de0756683ab1548d8b829660e0136'

[exercises.part01-e12_distinct_characters]
id = 188734
checksum = '8d276adb6f602ccca1b0b71035616259'

[exercises.part01-e13_reverse_dictionary]
id = 188736
checksum = '4fd3c1e6576c05e64f5f651f842ea5d2'

[exercises.part01-e14_find_matching]
id = 188738
checksum = '62f3ac44477e24a8fad5ba6653e26cf9'

[exercises.part01-e15_two_dice_comprehension]
id = 188726
checksum = '052823ea2dc32f04fdb37219d6875064'

[exercises.part01-e16_transform]
id = 188723
checksum = '947c90d87d144b9ea2438e567e760df7'

[exercises.part01-e17_positive_list]
id = 188724
checksum = '106446edf0e1ec7e4b0ffed03f058f25'

[exercises.part01-e18_acronyms]
id = 188725
checksum = '6ff7c1b2e7c92466debd7f610271158b'

[exercises.part01-e19_sum_equation]
id = 188733
checksum = '3c2468f5065992e44116b50b1f9a2f9c'

[exercises.part01-e20_usemodule]
id = 188730
checksum = '28f71bbc22dc24f598013f6e0491fea0'

[exercises.part02-e01_integers_in_brackets]
id = 188694
checksum = '431cf9180cc0c353e2893a35ac2374c0'

[exercises.part02-e02_file_listing]
id = 188696
checksum = 'a7b6f16c83c7f0150528a48c94c49cb1'

[exercises.part02-e03_red_green_blue]
id = 188699
checksum = 'd6479e6d74e0cd79a3f1fed04b10a30e'

[exercises.part02-e04_word_frequencies]
id = 188697
checksum = '836300a839065b39bcbdfb341df57fcc'

[exercises.part02-e05_summary]
id = 188706
checksum = 'a815feda70c1ef96e62d7ca3263dbfaf'

[exercises.part02-e06_file_count]
id = 188703
checksum = 'c9171fc30e3406204fee8e9f2069435b'

[exercises.part02-e07_file_extensions]
id = 188701
checksum = 'a0bf94652ace609c21d254f4078817c2'

[exercises.part02-e08_prepend]
id = 188708
checksum = 'ce3473fdd3f262eff82d9557ae419f16'

[exercises.part02-e09_rational]
id = 188695
checksum = 'e7b78a952836894fca30cd451edfec09'

[exercises.part02-e10_extract_numbers]
id = 188704
checksum = 'dff65a086340b67266871b04b0c84172'

[exercises.part02-e11_rows_and_columns]
id = 188698
checksum = '3a7254a9cc367897276fa6255759e7b8'

[exercises.part02-e12_row_and_column_vectors]
id = 188700
checksum = 'eb34d0001bbb79967260abe6853ebf88'

[exercises.part02-e13_diamond]
id = 188702
checksum = '4e3e28f101aedd57d97c239cca2212df'

[exercises.part02-e14_vector_lengths]
id = 188705
checksum = '1dbe7bfc0697a8cab191fbe3985e72d5'

[exercises.part02-e15_vector_angles]
id = 188707
checksum = '45e6a8c92899febc975d6471be332835'

[exercises.part02-e16_multiplication_table_revisited]
id = 188693
checksum = 'e0d5bede89ce32e17690b3e8eb02e2dd'

[exercises.part03-e01_column_comparison]
id = 188773
checksum = '0f200a31ccf497c1a7e7af8a65c72272'

[exercises.part03-e02_first_half_second_half]
id = 188778
checksum = '3b3e0fb94bd674c2eb4ebab2f8bd31e8'

[exercises.part03-e03_most_frequent_first]
id = 188782
checksum = '70ce3d3b7de674c699d6bcc93cce397f'

[exercises.part03-e04_matrix_power]
id = 188771
checksum = '37487d7c6a97d6364dc8ebe5043e2f4a'

[exercises.part03-e05_correlation]
id = 188781
checksum = '56d14e11f92c2b669db9ffaeb42e845e'

[exercises.part03-e06_meeting_lines]
id = 188779
checksum = '99b271998bc45f4d791131dbb471813e'

[exercises.part03-e07_meeting_planes]
id = 188783
checksum = '4c92d78319e5a98034094d53f7b2b087'

[exercises.part03-e08_almost_meeting_lines]
id = 188774
checksum = '0fd052365ce1895c372d93f4908b6825'

[exercises.part03-e09_multiple_graphs]
id = 188777
checksum = '131c98aa1b3037b9cec3544f13edacda'

[exercises.part03-e10_subfigures]
id = 188772
checksum = 'a2e850e244393776197cbd1462cdbbb7'

[exercises.part03-e11_to_grayscale]
id = 188770
checksum = '4bf51ae2787ca84a3194d9e969e68577'

[exercises.part03-e12_radial_fade]
id = 188776
checksum = '809064d36205fa66093d7dbaf0657d4d'

[exercises.part03-e13_read_series]
id = 188775
checksum = 'c13e59eeacee2b1abc99f90482aaf68b'

[exercises.part03-e14_operations_on_series]
id = 188780
checksum = 'fec8c98e3a3e888d71576c9e82e90a68'

[exercises.part03-e15_inverse_series]
id = 188769
checksum = '7d5d765c739d99368dc3e2e01689cd40'

[exercises.part04-e01_cities]
id = 188761
checksum = 'c57568f41d96e980217b01a966ba6a8a'

[exercises.part04-e02_powers_of_series]
id = 188754
checksum = '9a6fbcc5ae36c85c48649cf68b953974'

[exercises.part04-e03_municipal_information]
id = 188751
checksum = '821fc92a73f3b9188734d44e440c9c76'

[exercises.part04-e04_municipalities_of_finland]
id = 188759
checksum = 'a21b2284c4bcf405515845d429a59c76'

[exercises.part04-e05_swedish_and_foreigners]
id = 188767
checksum = '255b74473d4b47390369ab8fae23169a'

[exercises.part04-e06_growing_municipalities]
id = 188752
checksum = '90a1c536cb66198577dc8013eb917a3e'

[exercises.part04-e07_subsetting_with_loc]
id = 188755
checksum = '9dd60571a4bcbf19d972a6d01f6ec2b5'

[exercises.part04-e08_subsetting_by_positions]
id = 188758
checksum = 'fd68dd9bdfc9806b3a09fcd3d96a4fea'

[exercises.part04-e09_snow_depth]
id = 188764
checksum = 'f05756aadd42b47b6ff4112bdda9dc6a'

[exercises.part04-e10_average_temperature]
id = 188757
checksum = '55a807e3b40aa9877c2ce68a812af4f0'

[exercises.part04-e11_below_zero]
id = 188762
checksum = '5b02e36f9aacac5825bb65744d5c199c'

[exercises.part04-e12_cyclists]
id = 188753
checksum = '7b20fcd7a35971e983745097edf891f0'

[exercises.part04-e13_missing_value_types]
id = 188756
checksum = '6175b4576a21f4c5fd7734f52f7e24b9'

[exercises.part04-e14_special_missing_values]
id = 188760
checksum = 'c838314624462597c1b1251327fa3907'

[exercises.part04-e15_last_week]
id = 188765
checksum = 'e6d954442d899e51ca33eccae4424a11'

[exercises.part04-e16_split_date]
id = 188763
checksum = '8c5f0343a3f0cb97512593b6b60f9127'

[exercises.part04-e17_cleaning_data]
id = 188766
checksum = 'e8d7b7400e6f2bd4d2e4078444ddc70f'
